version: '3.9'

services:
  db:
    image: mariadb:11
    container_name: fullstack-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: seed_db
      MYSQL_USER: seed_user
      MYSQL_PASSWORD: seed_pwd
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fullstack-backend
    environment:
      SPRING_PROFILES_ACTIVE: dev-maria
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/seed_db
      SPRING_DATASOURCE_USERNAME: seed_user
      SPRING_DATASOURCE_PASSWORD: seed_pwd
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  db-data:
